services:
  db:
    image: postgres:16
    restart: always
    shm_size: "128mb"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10

  client:
    build: ./client
    depends_on:
      - server
    expose:
      - "3000"

  server:
    build: ./server
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3333"

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - client
      - server
