services:
  db:
    image: postgres
    restart: always
    shm_size: "128mb"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8084:8080"

  client:
    build: ./client
    depends_on:
      - server
    expose:
      - "5173"

  server:
    build: ./server
    depends_on:
      db:
        condition: service_healthy

    expose:
      - "3333"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - client
      - server
