services:
  db:
    image: postgres
    restart: always
    shm_size: "128mb"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8084:8080"

  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "5173:5173"

  server:
    build: ./server
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
